name: naturly
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.7.0 <4.0.0"

workspace:
  - packages/logger

dependencies:
  async: 2.13.0
  auto_route: ^10.0.1
  clock: 1.1.2
  collection: 1.19.1
  equatable: ^2.0.7
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_side_menu: ^0.5.41
  glassmorphism: ^3.0.0
  intl: 0.20.2
  logger:
    path: packages/logger
  nanoid: ^1.0.0
  package_info_plus: 8.3.0
  path: 1.9.1
  path_provider: 2.1.5
  rxdart: 0.28.0
  sentry_flutter: 8.14.2
  shared_preferences: 2.5.3
  stack_trace: 1.12.1
  stream_transform: 2.1.1
  supabase_flutter: ^2.8.4

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: 2.4.15
  flutter_gen_runner: 5.10.0
  

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/icons/
    - assets/images/
flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 80
