final dishes = {
  "morning": [
    {
      "title": "Овсянка с ягодами",
      "mealType": 'Завтрак',
      "products": [
        {
          "title": "Овсянка",
          "price": 50,
          "protein": 5,
          "fats": 2,
          "carbs": 30,
          "ccal": 150,
          "productGroup": "grainsAndPotatoes",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 150,
        },
        {
          "title": "Молоко",
          "price": 40,
          "protein": 8,
          "fats": 5,
          "carbs": 12,
          "ccal": 150,
          "productGroup": "dairyAndDairyProducts",
          "fishType": null,
          "proteinType": "milk",
          "meatType": null,
          "quantity": 200,
        }
      ],
      "calories": 300,
      "restrictions": ["glutenFree"],
      "totalPrice": 90,
      "missingProducts": [],
      "protein": 13,
      "fats": 7,
      "carbs": 42,
      "totalMissingCost": null
    },
    {
      "title": "Тост с авокадо",
      "mealType": 'Завтрак',
      "products": [
        {
          "title": "Хлеб",
          "price": 30,
          "protein": 2,
          "fats": 1,
          "carbs": 15,
          "ccal": 80,
          "productGroup": "grainsAndPotatoes",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        },
        {
          "title": "Авокадо",
          "price": 70,
          "protein": 2,
          "fats": 15,
          "carbs": 12,
          "ccal": 160,
          "productGroup": "vegetablesFruitsAndBerries",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 150,
        }
      ],
      "calories": 240,
      "restrictions": ["noDairy"],
      "totalPrice": 100,
      "missingProducts": [],
      "protein": 4,
      "fats": 16,
      "carbs": 27,
      "totalMissingCost": null
    },
    {
      "title": "Йогурт с орехами",
      "mealType": 'Завтрак',
      "products": [
        {
          "title": "Йогурт",
          "price": 80,
          "protein": 6,
          "fats": 4,
          "carbs": 15,
          "ccal": 130,
          "productGroup": "dairyAndDairyProducts",
          "fishType": null,
          "proteinType": "yogurt",
          "meatType": null,
          "quantity": 150,
        },
        {
          "title": "Орехи",
          "price": 100,
          "protein": 7,
          "fats": 15,
          "carbs": 8,
          "ccal": 200,
          "productGroup": "addedFatsNutsSeedsAndOilyFruits",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 110,
        }
      ],
      "calories": 330,
      "restrictions": ["noGluten"],
      "totalPrice": 180,
      "missingProducts": [],
      "protein": 13,
      "fats": 19,
      "carbs": 23,
      "totalMissingCost": null
    },
    {
      "title": "Каша гречневая с яйцом",
      "mealType": 'Завтрак',
      "products": [
        {
          "title": "Гречка",
          "price": 40,
          "protein": 3,
          "fats": 1,
          "carbs": 30,
          "ccal": 150,
          "productGroup": "grainsAndPotatoes",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 110,
        },
        {
          "title": "Яйцо",
          "price": 15,
          "protein": 6,
          "fats": 5,
          "carbs": 0,
          "ccal": 70,
          "productGroup": "fishPoultryMeatAndEggs",
          "fishType": null,
          "proteinType": null,
          "meatType": "chicken",
          "quantity": 90,
        }
      ],
      "calories": 220,
      "restrictions": ["glutenFree"],
      "totalPrice": 55,
      "missingProducts": [],
      "protein": 9,
      "fats": 6,
      "carbs": 30,
      "totalMissingCost": null
    },
    {
      "title": "Банан с медом",
      "mealType": 'Завтрак',
      "products": [
        {
          "title": "Банан",
          "price": 50,
          "protein": 1,
          "fats": 0,
          "carbs": 27,
          "ccal": 105,
          "quantity": 110,
          "productGroup": "vegetablesFruitsAndBerries",
          "fishType": null,
          "proteinType": null,
          "meatType": null
        },
        {
          "title": "Мед",
          "price": 60,
          "protein": 0,
          "fats": 0,
          "carbs": 17,
          "ccal": 64,
          "productGroup": "sugarSweetsAndSnacks",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 40,
        }
      ],
      "calories": 169,
      "restrictions": ["noDairy"],
      "totalPrice": 110,
      "missingProducts": [],
      "protein": 1,
      "fats": 0,
      "carbs": 44,
      "totalMissingCost": null
    }
  ],
  "lunch": [
    {
      "title": "Салат с курицей и овощным супом",
      "mealType": 'Обед',
      "products": [
        {
          "title": "Куриная грудка",
          "price": 150,
          "protein": 30,
          "fats": 5,
          "carbs": 0,
          "ccal": 165,
          "productGroup": "fishPoultryMeatAndEggs",
          "fishType": null,
          "proteinType": null,
          "meatType": "chicken",
          "quantity": 80,
        },
        {
          "title": "Листья салата",
          "price": 20,
          "protein": 1,
          "fats": 0,
          "carbs": 2,
          "ccal": 10,
          "productGroup": "vegetablesFruitsAndBerries",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 200,
        },
        {
          "title": "Овощной суп",
          "price": 80,
          "protein": 3,
          "fats": 2,
          "carbs": 10,
          "ccal": 80,
          "productGroup": "soupsAndBroths",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        },
        {
          "title": "Куринный бульон",
          "price": 80,
          "protein": 1,
          "fats": 10,
          "carbs": 5,
          "ccal": 100,
          "productGroup": "soupsAndBroths",
          "fishType": null,
          "proteinType": null,
          "meatType": "chicken",
          "quantity": 100,
        }
      ],
      "calories": 255,
      "restrictions": ["lowCarb"],
      "totalPrice": 250,
      "missingProducts": [],
      "protein": 34,
      "fats": 7,
      "carbs": 12,
      "totalMissingCost": null
    },
    {
      "title": "Том Ям с креветками",
      "mealType": 'Обед',
      "products": [
        {
          "title": "Креветки",
          "price": 200,
          "protein": 30,
          "fats": 2,
          "carbs": 0,
          "ccal": 140,
          "productGroup": "fishPoultryMeatAndEggs",
          "fishType": "shrimp",
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        },
        {
          "title": "Кокосовое молоко",
          "price": 80,
          "protein": 1,
          "fats": 10,
          "carbs": 5,
          "ccal": 100,
          "productGroup": "dairyAndDairyProducts",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        },
        {
          "title": "Куринный бульон",
          "price": 80,
          "protein": 1,
          "fats": 10,
          "carbs": 5,
          "ccal": 100,
          "productGroup": "soupsAndBroths",
          "fishType": null,
          "proteinType": null,
          "meatType": "chicken",
          "quantity": 100,
        }
      ],
      "calories": 240,
      "restrictions": ["noGluten"],
      "totalPrice": 280,
      "missingProducts": [],
      "protein": 31,
      "fats": 12,
      "carbs": 5,
      "totalMissingCost": null
    },
    {
      "title": "Гречка с мясом",
      "mealType": 'Обед',
      "products": [
        {
          "title": "Гречка",
          "price": 40,
          "protein": 3,
          "fats": 1,
          "carbs": 30,
          "ccal": 150,
          "productGroup": "grainsAndPotatoes",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        },
        {
          "title": "Говядина",
          "price": 150,
          "protein": 30,
          "fats": 10,
          "carbs": 0,
          "ccal": 250,
          "productGroup": "fishPoultryMeatAndEggs",
          "fishType": null,
          "proteinType": null,
          "meatType": "beef",
          "quantity": 100,
        }
      ],
      "calories": 400,
      "restrictions": ["noDairy"],
      "totalPrice": 190,
      "missingProducts": [],
      "protein": 33,
      "fats": 11,
      "carbs": 30,
      "totalMissingCost": null,
    },
    {
      "title": "Запеченная рыба с картошкой",
      "mealType": 'Обед',
      "products": [
        {
          "title": "Рыба",
          "price": 200,
          "protein": 25,
          "fats": 5,
          "carbs": 0,
          "ccal": 150,
          "productGroup": "fishPoultryMeatAndEggs",
          "fishType": "salmon",
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        },
        {
          "title": "Картошка",
          "price": 40,
          "protein": 2,
          "fats": 0,
          "carbs": 30,
          "ccal": 130,
          "productGroup": "grainsAndPotatoes",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        }
      ],
      "calories": 280,
      "restrictions": ["noGluten"],
      "totalPrice": 240,
      "missingProducts": [],
      "protein": 27,
      "fats": 5,
      "carbs": 30,
      "totalMissingCost": null
    },
  ],
  "snack": [
    {
      "title": "Орехи с медом",
      "mealType": 'Перекус',
      "products": [
        {
          "title": "Орехи",
          "price": 100,
          "protein": 7,
          "fats": 15,
          "carbs": 8,
          "ccal": 200,
          "productGroup": "addedFatsNutsSeedsAndOilyFruits",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        },
        {
          "title": "Мед",
          "price": 60,
          "protein": 0,
          "fats": 0,
          "carbs": 17,
          "ccal": 64,
          "productGroup": "sugarSweetsAndSnacks",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        }
      ],
      "calories": 264,
      "restrictions": ["noDairy"],
      "totalPrice": 160,
      "missingProducts": [],
      "protein": 7,
      "fats": 15,
      "carbs": 25,
      "totalMissingCost": null
    },
    {
      "title": "Йогурт с фруктами",
      "mealType": 'Перекус',
      "products": [
        {
          "title": "Йогурт",
          "price": 80,
          "protein": 6,
          "fats": 4,
          "carbs": 15,
          "ccal": 130,
          "productGroup": "dairyAndDairyProducts",
          "fishType": null,
          "proteinType": "yogurt",
          "meatType": null,
          "quantity": 100,
        },
        {
          "title": "Ягоды",
          "price": 50,
          "protein": 1,
          "fats": 0,
          "carbs": 12,
          "ccal": 50,
          "productGroup": "vegetablesFruitsAndBerries",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        }
      ],
      "calories": 180,
      "restrictions": ["noGluten"],
      "totalPrice": 130,
      "missingProducts": [],
      "protein": 7,
      "fats": 4,
      "carbs": 27,
      "totalMissingCost": null
    },
    {
      "title": "Тост с авокадо",
      "mealType": 'Перекус',
      "products": [
        {
          "title": "Хлеб",
          "price": 30,
          "protein": 2,
          "fats": 1,
          "carbs": 15,
          "ccal": 80,
          "productGroup": "grainsAndPotatoes",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        },
        {
          "title": "Авокадо",
          "price": 70,
          "protein": 2,
          "fats": 15,
          "carbs": 12,
          "ccal": 160,
          "productGroup": "vegetablesFruitsAndBerries",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        }
      ],
      "calories": 240,
      "restrictions": ["noDairy"],
      "totalPrice": 100,
      "missingProducts": [],
      "protein": 4,
      "fats": 16,
      "carbs": 27,
      "totalMissingCost": null
    },
    {
      "title": "Смузи с бананом",
      "mealType": 'Перекус',
      "products": [
        {
          "title": "Банан",
          "price": 50,
          "protein": 1,
          "fats": 0,
          "carbs": 27,
          "ccal": 105,
          "productGroup": "vegetablesFruitsAndBerries",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        },
        {
          "title": "Йогурт",
          "price": 80,
          "protein": 6,
          "fats": 4,
          "carbs": 15,
          "ccal": 130,
          "productGroup": "dairyAndDairyProducts",
          "fishType": null,
          "proteinType": "yogurt",
          "meatType": null,
          "quantity": 100,
        }
      ],
      "calories": 235,
      "restrictions": ["glutenFree"],
      "totalPrice": 130,
      "missingProducts": [],
      "protein": 7,
      "fats": 4,
      "carbs": 42,
      "totalMissingCost": null
    },
    {
      "title": "Фрукты",
      "mealType": 'Перекус',
      "products": [
        {
          "title": "Яблоки",
          "price": 40,
          "protein": 1,
          "fats": 0,
          "carbs": 25,
          "ccal": 95,
          "productGroup": "vegetablesFruitsAndBerries",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        }
      ],
      "calories": 95,
      "restrictions": ["vegan"],
      "totalPrice": 40,
      "missingProducts": [],
      "protein": 1,
      "fats": 0,
      "carbs": 25,
      "totalMissingCost": null
    }
  ],
  "dinner": [
    {
      "title": "Паста с соусом",
      "mealType": 'Ужин',
      "products": [
        {
          "title": "Паста",
          "price": 50,
          "protein": 7,
          "fats": 1,
          "carbs": 25,
          "ccal": 120,
          "productGroup": "grainsAndPotatoes",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        },
        {
          "title": "Соус томатный",
          "price": 60,
          "protein": 2,
          "fats": 5,
          "carbs": 10,
          "ccal": 80,
          "productGroup": "sugarSweetsAndSnacks",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        }
      ],
      "calories": 200,
      "restrictions": ["vegan"],
      "totalPrice": 110,
      "missingProducts": [],
      "protein": 9,
      "fats": 6,
      "carbs": 35,
      "totalMissingCost": null
    },
    {
      "title": "Курица с картофелем",
      "mealType": 'Ужин',
      "products": [
        {
          "title": "Курица",
          "price": 120,
          "protein": 20,
          "fats": 10,
          "carbs": 0,
          "ccal": 150,
          "productGroup": "fishPoultryMeatAndEggs",
          "fishType": null,
          "proteinType": null,
          "meatType": "chicken",
          "quantity": 100,
        },
        {
          "title": "Картофель",
          "price": 50,
          "protein": 2,
          "fats": 0,
          "carbs": 25,
          "ccal": 100,
          "productGroup": "grainsAndPotatoes",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        }
      ],
      "calories": 250,
      "restrictions": ["noDairy"],
      "totalPrice": 170,
      "missingProducts": [],
      "protein": 22,
      "fats": 10,
      "carbs": 25,
      "totalMissingCost": null
    },
    {
      "title": "Ризотто с грибами",
      "mealType": 'Ужин',
      "products": [
        {
          "title": "Рис",
          "price": 60,
          "protein": 5,
          "fats": 0,
          "carbs": 45,
          "ccal": 200,
          "productGroup": "grainsAndPotatoes",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        },
        {
          "title": "Грибы",
          "price": 70,
          "protein": 5,
          "fats": 1,
          "carbs": 10,
          "ccal": 80,
          "productGroup": "vegetablesFruitsAndBerries",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        }
      ],
      "calories": 280,
      "restrictions": ["vegan"],
      "totalPrice": 130,
      "missingProducts": [],
      "protein": 10,
      "fats": 3,
      "carbs": 55,
      "totalMissingCost": null
    },
    {
      "title": "Тунец с рисом",
      "mealType": 'Ужин',
      "products": [
        {
          "title": "Тунец",
          "price": 150,
          "protein": 25,
          "fats": 5,
          "carbs": 0,
          "ccal": 180,
          "productGroup": "fishPoultryMeatAndEggs",
          "fishType": "tuna",
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        },
        {
          "title": "Рис",
          "price": 60,
          "protein": 5,
          "fats": 0,
          "carbs": 45,
          "ccal": 200,
          "productGroup": "grainsAndPotatoes",
          "fishType": null,
          "proteinType": null,
          "meatType": null,
          "quantity": 100,
        }
      ],
      "calories": 380,
      "restrictions": ["glutenFree"],
      "totalPrice": 210,
      "missingProducts": [],
      "protein": 30,
      "fats": 5,
      "carbs": 45,
      "totalMissingCost": null
    },
  ]
};

final availableProductsJson = [
  {
    "title": "Овсянка",
    "price": 50,
    "protein": 5,
    "fats": 2,
    "carbs": 30,
    "ccal": 150,
    "productGroup": "grainsAndPotatoes",
    "fishType": null,
    "proteinType": null,
    "meatType": null,
    "quantity": 150,
  },
  {
    "title": "Молоко",
    "price": 40,
    "protein": 8,
    "fats": 5,
    "carbs": 12,
    "ccal": 150,
    "productGroup": "dairyAndDairyProducts",
    "fishType": null,
    "proteinType": "milk",
    "meatType": null,
    "quantity": 200,
  },
  {
    "title": "Семга",
    "price": 500,
    "protein": 20,
    "fats": 15,
    "carbs": 0,
    "ccal": 250,
    "productGroup": "fishPoultryMeatAndEggs",
    "fishType": "salmon",
    "proteinType": null,
    "meatType": null,
    "quantity": 1100,
  },
  {
    "title": "Куриная грудка",
    "price": 250,
    "protein": 30,
    "fats": 5,
    "carbs": 0,
    "ccal": 180,
    "productGroup": "fishPoultryMeatAndEggs",
    "fishType": null,
    "proteinType": null,
    "meatType": "chicken",
    "quantity": 500,
  },
  {
    "title": "Творог",
    "price": 150,
    "protein": 18,
    "fats": 10,
    "carbs": 3,
    "ccal": 200,
    "productGroup": "dairyAndDairyProducts",
    "fishType": null,
    "proteinType": "cottageCheese",
    "meatType": null,
    "quantity": 900,
  },
  {
    "title": "Картофель",
    "price": 50,
    "protein": 2,
    "fats": 0,
    "carbs": 20,
    "ccal": 90,
    "productGroup": "grainsAndPotatoes",
    "fishType": null,
    "proteinType": null,
    "meatType": null,
    "quantity": 1200,
  },
  {
    "title": "Орехи",
    "price": 300,
    "protein": 25,
    "fats": 50,
    "carbs": 15,
    "ccal": 600,
    "productGroup": "addedFatsNutsSeedsAndOilyFruits",
    "fishType": null,
    "proteinType": null,
    "meatType": null,
    "quantity": 100,
  }
];
